# -*- coding: utf-8 -*-
"""100006644_Week1_Metadata_CreditRisk.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VuyXz1hMRALjhNFGPVf3gLoKF6ppgXeY

# Week 1 – Exercise 1 – Individual – Metadata Creation
## Name: Anushka Sawant
## Matriculation Number: 100006644

# Week 1 — Exercise 1: Individual Metadata Creation

## Goal
- Practice creating metadata by applying what you learned in class to a dataset of your choice.

## Task
- Select any publicly available dataset, for example from Kaggle, Zenodo, or Figshare, and create the following:
- DataCite metadata in XML format
- schema.org metadata in JSON-LD format using @type: Dataset


## Submission / GitHub Workflow

Upload your individual exercise to your own GitHub repository
Organize your repository clearly by week and exercise
For group projects, all group members may collaborate and keep their work in GitHub
Only one group representative should submit the final GitHub repository link
The README file must clearly include the names of all group members

## File Naming
Please use clear filenames, for example:

- yourdataset_datacite.xml
- yourdataset_schemaorg.json

## Dataset used: Credit Risk Benchmark Dataset (Kaggle)
https://www.kaggle.com/datasets/adilshamim8/credit-risk-benchmark-dataset
"""

from pathlib import Path
import pandas as pd
import hashlib
import json
import pandas as pd
from pathlib import Path
from IPython.display import display, Markdown
from pathlib import Path
from urllib.request import urlretrieve
from lxml import etree
from google.colab import files

"""## 1. Load Dataset"""

GITHUB_RAW_BASE = "https://raw.githubusercontent.com/AnushkaSDBI/Data-Management/main"

required_files = [
    ("Data/Credit%20Risk%20Benchmark%20Dataset.csv", "Data/Credit%20Risk%20Benchmark%20Dataset.csv"),
]

for local_rel, github_rel in required_files:
    local_path = Path(local_rel)
    if not local_path.exists():
        local_path.parent.mkdir(parents=True, exist_ok=True)
        url = f"{GITHUB_RAW_BASE}/{github_rel}"
        urlretrieve(url, local_path)
        print(f"Downloaded: {local_path}")

print("Bootstrap complete.")

repo_root = Path().resolve()
csv_path = repo_root / "Data" / "Credit%20Risk%20Benchmark%20Dataset.csv"

print("Expected CSV path:", csv_path)
print("File exists:", csv_path.exists())

df = pd.read_csv(csv_path)
display(df)

"""## 2. Dataset Profiling"""

file_size = csv_path.stat().st_size

sha = hashlib.sha256()
with csv_path.open('rb') as f:
    for chunk in iter(lambda: f.read(1024*1024), b''):
        sha.update(chunk)

checksum = sha.hexdigest()

summary = {
    'rows': len(df),
    'columns': df.shape[1],
    'size_bytes': file_size,
    'sha256': checksum
}

print(json.dumps(summary, indent=2))

"""## 3. Column Schema Inspection"""

for c in df.columns:
    print(c, '->', df[c].dtype)

"""## 4. Metadata Dictionary"""

META = {
    'identifier': '10.1234/credit-risk-benchmark',
    'title': 'Credit Risk Benchmark Dataset',
    'publisher': 'Kaggle',
    'publicationYear': '2023',
    'creators': [{'name': 'adilshamim8'}],
    'description': f'Dataset with {len(df)} rows and {df.shape[1]} columns for credit risk prediction.',
    'subjects': list(df.columns),
    'format': 'text/csv',
    'rows': len(df),
    'columns': df.shape[1],
    'size_bytes': file_size,
    'sha256': checksum
}

"""## 5. DataCite XML Generation"""

NS = 'http://datacite.org/schema/kernel-4'
resource = etree.Element(f'{{{NS}}}resource')

etree.SubElement(resource, 'identifier', identifierType='DOI').text = META['identifier']

creators = etree.SubElement(resource, 'creators')
for c in META['creators']:
    creator = etree.SubElement(creators, 'creator')
    etree.SubElement(creator, 'creatorName').text = c['name']

titles = etree.SubElement(resource, 'titles')
etree.SubElement(titles, 'title').text = META['title']

etree.SubElement(resource, 'publisher').text = META['publisher']
etree.SubElement(resource, 'publicationYear').text = META['publicationYear']

subjects = etree.SubElement(resource, 'subjects')
for s in META['subjects']:
    etree.SubElement(subjects, 'subject').text = str(s)

desc = etree.SubElement(resource, 'descriptions')
etree.SubElement(desc, 'description', descriptionType='Abstract').text = META['description']

xml_bytes = etree.tostring(resource, pretty_print=True, xml_declaration=True, encoding='UTF-8')
open('credit_risk_datacite.xml','wb').write(xml_bytes)

print(xml_bytes.decode())

"""## 6. schema.org JSON-LD"""

schema = {
    '@context': 'https://schema.org/',
    '@type': 'Dataset',
    'name': META['title'],
    'description': META['description'],
    'creator': [{'@type': 'Person', 'name': c['name']} for c in META['creators']],
    'publisher': {'@type': 'Organization', 'name': META['publisher']},
    'keywords': META['subjects'],
    'encodingFormat': META['format'],
    'url': 'https://www.kaggle.com/datasets/adilshamim8/credit-risk-benchmark-dataset'
}

json.dump(schema, open('credit_risk_schemaorg.json','w'), indent=2)

print(json.dumps(schema, indent=2))

"""## 7. Validation
Checking XML and JSON-LD structure
"""

xml_check = etree.fromstring(open('credit_risk_datacite.xml','rb').read())
json_check = json.load(open('credit_risk_schemaorg.json'))

print('XML root:', xml_check.tag)
print('JSON type:', json_check['@type'])

# download XML
files.download("credit_risk_datacite.xml")

# download JSON-LD
files.download("credit_risk_schemaorg.json")

"""## Conclusion

This notebook demonstrates a full metadata pipeline including dataset profiling, DataCite XML generation, schema.org JSON-LD creation, and validation on 2024 Credit Risk Dataset.
"""