# -*- coding: utf-8 -*-
"""100006644_dublin_core_parsing.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12fRrJIm2hIX8JU5m-iBiJuEfaspqBdsH

# 03 Day 2 Dublin Core Parsing
## Name: Anushka Sawant
## Matriculation Number: 100006644

# Notebook Bootstrap
"""

# Notebook bootstrap: download required files from GitHub if missing
from pathlib import Path
from urllib.request import urlretrieve

GITHUB_RAW_BASE = "https://raw.githubusercontent.com/MehrdadJalali-AI/data-management-teaching-materials/main"

required_files = [
    ("data/metadata/climate_dataset_dublin_core.xml", "data/metadata/climate_dataset_dublin_core.xml"),
]

for local_rel, github_rel in required_files:
    local_path = Path(local_rel)
    if not local_path.exists():
        local_path.parent.mkdir(parents=True, exist_ok=True)
        url = f"{GITHUB_RAW_BASE}/{github_rel}"
        urlretrieve(url, local_path)
        print(f"Downloaded: {local_path}")
    else:
        print(f"Already available: {local_path}")

print("Bootstrap completed.")

"""# Day 2: Dublin Core Parsing, Step by Step

In this notebook, we work with a **Dublin Core XML metadata record** for the teaching dataset **"2025 Global Climate Data"**.

## Learning goals
By the end of this notebook, students should be able to:
- understand what a Dublin Core metadata record looks like,
- identify key metadata fields such as title, creator, identifier, and description,
- parse XML metadata step by step in Python,
- convert parsed metadata into a clean table,
- connect metadata fields to the FAIR principles, especially **Findable** and **Reusable**.

## Why this matters
Dublin Core is a simple and widely used metadata standard. It is useful for showing the basic idea of metadata before moving to richer standards such as DataCite and schema.org.

## 1: Locate the metadata file

We first define the path to the local XML file that was downloaded by the bootstrap cell.
"""

from pathlib import Path

# Define path to the XML metadata file
xml_path = Path("data/metadata/climate_dataset_dublin_core.xml")

# Show absolute path for verification/debugging
print("Metadata path:", xml_path.resolve())

# Check if file exists before further processing
print("File exists:", xml_path.exists())

"""
## 2: Read the XML file as plain text

Before parsing, it is useful to quickly inspect the raw XML so students can see what the metadata record looks like.
"""

raw_xml = xml_path.read_text(encoding="utf-8")
print(raw_xml[:1500])

"""
## 3: Import Python libraries

We use:
- `xml.etree.ElementTree` to parse XML,
- `pandas` to create a readable table.
"""

# # ElementTree module for parsing XML and navigating structured metadata
# (e.g., Dublin Core, DataCite XML) but JSON handling for schema.org (JSON-LD) metadata structures
import xml.etree.ElementTree as ET

import pandas as pd

"""
## 4: Parse the XML and inspect the root element

This helps students understand that XML is a tree structure.
"""

# Parse XML file into a tree structure
tree = ET.parse(xml_path)

# Access the root element (starting point of the XML structure)
root = tree.getroot()

# Show XML structure
print(ET.tostring(root, encoding="unicode"))

# Show the main tag of the XML
print("Root tag:", root.tag)

# Count only the first-level child elements (not nested ones)
print("Number of direct child elements:", len(list(root)))
# Show full XML content as a string

"""## Interpret the fields from a metadata perspective

Each field supports a different purpose:

- **title** → helps users discover the dataset,
- **creator** → shows authorship and responsibility,
- **identifier** → provides a persistent reference,
- **description** → explains the content,
- **subject** → improves search and classification,
- **format** → gives a clue about technical usability,
- **date** → supports versioning and context.

## Connect the record to FAIR principles

This is not a full FAIR evaluation, but it shows how metadata supports FAIR.

### Findable
- strengthened by: **title**, **subject**, **identifier**

### Accessible
- can be supported when the identifier points to a reachable landing page or repository record

### Interoperable
- partly supported by structured XML and standard metadata fields

### Reusable
- strengthened by: **description**, **creator**, **date**, **format**
"""

fair_view = pd.DataFrame(
    [
        {"FAIR_principle": "Findable", "Relevant_fields": "title, subject, identifier", "Comment": "The dataset can be discovered and referenced more easily."},
        {"FAIR_principle": "Accessible", "Relevant_fields": "identifier", "Comment": "Accessibility depends on whether the identifier resolves to an accessible record."},
        {"FAIR_principle": "Interoperable", "Relevant_fields": "standardized XML structure, format", "Comment": "Structured metadata improves machine processing."},
        {"FAIR_principle": "Reusable", "Relevant_fields": "creator, description, date, format", "Comment": "Contextual fields help others understand and reuse the data."},
    ]
)

fair_view

"""
## Discuss possible weaknesses

Even when a metadata file is valid, it may still be limited.

Possible weaknesses to discuss in class:
- missing license information,
- limited provenance details,
- too few subject keywords,
- no explicit relation to versions or related datasets,
- weak description quality.

These points are useful to show students that **metadata quality** matters, not only metadata presence.
"""

weaknesses = [
    "No explicit license field shown in this simple Dublin Core example.",
    "The description may still be too short for full reuse.",
    "Subject terms may need to be richer and more standardized.",
    "No explicit version or provenance field is included.",
]

for i, item in enumerate(weaknesses, start=1):
    print(f"{i}. {item}")