# -*- coding: utf-8 -*-
"""100006644_week2_exercise_individual_data quality audit.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17VViqKzFpx-D0k__2ajO2WJAodCWXcfu

# Week 2 – Exercise – Individual – Data Quality Audit
## Name: Anushka Sawant
## Matriculation Number: 100006644

## **TASK 1**
### **Dataset Description & Business use case:**
**Dataset Overview:**
The dataset comprises 11 transaction records — including one confirmed duplicate — spanning nine attributes:
`transaction_id`, `customer_id`, `transaction_date`, `amount`, `currency`, `payment_method`, `status`, `region`, and `last_updated`.
While small in volume, the dataset reflects the structure of a production-grade financial ledger and serves as a representative sample for quality assessment.

**Business Use Case:**
This data is consistent with a Financial Auditing and Revenue Recognition pipeline. In an operational context, it supports tracking of regional sales performance, payment method distribution, and transaction lifecycle status. Downstream consumers of this data likely include finance teams running month-end close reports, BI dashboards monitoring KPIs, and compliance functions validating currency and payment records.

**Impact of Current Data Quality Issues:**
The existing quality gaps — including missing identifiers, invalid amounts, inconsistent region labels, and duplicate records — introduce compounding risks across the business:
- **Tax & Compliance:** Malformed or missing amounts distort taxable revenue calculations and may trigger audit flags.
- **KPI Reliability:** Duplicate transactions inflate sales figures, while null customer IDs break attribution models used in performance reporting.
- **Regional Analysis:** Inconsistent region labels fragment geographic aggregations, making cross-region comparisons unreliable.
- **Pipeline Stability:** Type inconsistencies in `amount` and `transaction_date` will cause downstream failures in any automated ETL or ML feature engineering step.

**Recommendation:**
Before this dataset can be used in any reporting or analytical workflow, a structured remediation pass — covering deduplication, type casting, imputation, and label standardization — is essential to restore data integrity and business trust.

### Importing Packages
"""

import pandas as pd
import numpy as np
from pathlib import Path
from urllib.request import urlretrieve

"""### Data Loading"""

GITHUB_RAW_BASE = "https://raw.githubusercontent.com/AnushkaSDBI/Data-Management/main"

required_files = [
    ("Data/week2_customer_transactions_messy.csv", "Data/week2_customer_transactions_messy.csv"),
]

for local_rel, github_rel in required_files:
    local_path = Path(local_rel)
    if not local_path.exists():
        local_path.parent.mkdir(parents=True, exist_ok=True)
        url = f"{GITHUB_RAW_BASE}/{github_rel}"
        urlretrieve(url, local_path)
        print(f"Downloaded: {local_path}")

print("Bootstrap complete.")

repo_root = Path().resolve()
csv_path = repo_root / "Data" / "week2_customer_transactions_messy.csv"

print("Expected CSV path:", csv_path)
print("File exists:", csv_path.exists())

df = pd.read_csv(csv_path)
display(df)

"""## Data Description"""

# Dataset information
display(df.info())

# Data Description
display(df.describe())

# Null values
print(df.isnull().sum())

"""## **TASK 2**
### **Issues by Dimension**
"""

quality_report = pd.DataFrame([
    ['Null customer IDs', 'Completeness', 'Breaks customer segmentation and attribution models.'],
    ['Duplicate transactions', 'Uniqueness', 'Inflates revenue metrics and distorts trend analysis.'],
    ['Invalid date entries', 'Validity', 'Corrupts time-series analysis and reporting periods.'],
    ['Inconsistent region labels', 'Consistency', 'Prevents reliable geographic segmentation of data.']
], columns=['Issue', 'Dimension', 'Impact'])
quality_report

"""## **TASK 3**
### **KPI Calculations**
"""

# Completeness Rate (Customer ID and Amount)
missing_count = df[['customer_id', 'amount']].isnull().any(axis=1).sum()
completeness_rate = ((len(df) - missing_count) / len(df)) * 100

# Duplication Rate
dup_count = df.duplicated().sum()
duplication_rate = (dup_count / len(df)) * 100

# Validity Error Rate (Amount > 0 and realistic)
valid_amount = df['amount'].apply(lambda x: 0 < x < 1000000 if pd.notnull(x) else False)
error_rate = ((len(df) - valid_amount.sum()) / len(df)) * 100

# # Consistency Rate (Region Labels)
valid_regions = {'DE', 'FR', 'NL'}  # define your expected values
inconsistent_region = df['region'].str.strip().apply(
    lambda x: x not in valid_regions if pd.notnull(x) else False
)
inconsistency_rate = (inconsistent_region.sum() / len(df)) * 100

print(f"KPI Summary:")
print(f"1. Completeness Rate: {completeness_rate:.2f}%")
print(f"2. Duplication Rate: {duplication_rate:.2f}%")
print(f"3. Error Rate (Validity): {error_rate:.2f}%")
print(f"4. Inconsistency Rate (Region): {inconsistency_rate:.2f}%")

"""### **KPI Interpretation**
**1. Completeness Rate (81.82%):**

Meaning: Roughly 1 in 5 records is missing a customer_id, an amount, or both.

Impact: This level of missing data is significant. In financial reporting, it creates "revenue leakage" — transactions that can't be traced to a customer or assigned a correct value.

**2. Duplication Rate (9.09%):**

Meaning: Nearly 1 in 10 rows is an exact copy of another row in the dataset.

Impact: This points to a likely problem in the ingestion pipeline — such as a job running more than once or missing deduplication logic — and will cause sales figures to be overstated by close to 10%.

**3. Error Rate / Validity (36.36%):**

Meaning: More than a third of records fail the amount validity check — values are either non-numeric, negative, or unrealistically large (above $1,000,000).

Impact: This is the most critical issue. It signals that the amount column is fundamentally unreliable and may require a full data audit or a rethink of how that field is being captured at the source.

**4. Inconsistency Rate (18.18%):**

Meaning: 18% of records contain region labels that don't conform to the expected set of valid values — likely due to free-text entry, abbreviations, or casing variations (e.g. "DE", "de").

Impact: This undermines any geographic segmentation or regional reporting. Aggregations by region will be fragmented and misleading until a standardized lookup or input validation is enforced upstream.

## **TASK 4**
### **Validation Rules**
"""

rules={
'transaction_id_required': df['transaction_id'].isna() | (df['transaction_id'].astype(str).str.strip()==''),
'amount_non_negative': pd.to_numeric(df['amount'], errors='coerce')<0,
'transaction_date_valid': pd.to_datetime(df['transaction_date'], errors='coerce', format='mixed').isna(),
}
pd.DataFrame({k:int(v.sum()) for k,v in rules.items()}, index=['affected_rows']).T

"""## **TASK 5**
### **Audit Summary**
"""

audit_data = [
    ['Invalid/Outlier Amounts', '36.36%', 'Critical', 'Verify values > $1M and handle negative entries.'],
    ['Missing ID or Amount', '18.18%', 'High', 'Isolate rows missing customer_id for reconciliation.'],
    ['Duplicate Transactions', '9.09%', 'Medium', 'Apply drop_duplicates() to stabilize revenue reporting.'],
    ['Inconsistent Region Labels', '18.18%', 'Medium', 'Standardize values against a valid_regions lookup and enforce input validation.']
]

audit_summary = pd.DataFrame(audit_data, columns=['issue_type', 'affected_rows', 'severity', 'recommended_next_action'])
audit_summary

"""## **TASK 6**
### **Recommended Cleaning Actions for next week:**
"""

remediation_plan = pd.DataFrame([
    [1, 'Schema Normalization', 'Critical', 'Standardize all column headers with .str.strip().lower() to prevent KeyErrors caused by whitespace or casing.'],
    [2, 'Record Deduplication', 'High', 'Run drop_duplicates() to eliminate the ~9% redundant rows and enforce unique transaction_ids throughout.'],
    [3, 'Financial Type Casting', 'Critical', 'Cast amount to numeric and transaction_date to datetime using errors="coerce" to surface unparseable entries.'],
    [4, 'Strategic Imputation', 'Medium', 'Replace missing amount values with the per-category median to maintain the underlying distribution.'],
    [5, 'Label Standardization', 'Low', 'Apply a mapping dictionary (e.g., {"electr": "Electronics"}) to consolidate fragmented category labels.']
], columns=['step', 'action_item', 'priority', 'expected_outcome'])

display(remediation_plan)

"""## **Bonus (Audit Function)**"""

rules = {
    'Invalid/Outlier Amounts': ~df['amount'].apply(lambda x: 0 < x < 1000000 if pd.notnull(x) else False),
    'Missing ID or Amount': df[['customer_id', 'amount']].isnull().any(axis=1),
    'Duplicate Transactions': df.duplicated(),
    'Inconsistent Region Labels': df['region'].str.strip().apply(
        lambda x: x not in {'DE', 'FR', 'NL'} if pd.notnull(x) else False
    )
}

def summarize_rule_violations(rule_dictionary):
    return pd.DataFrame({
        'rule_name': list(rule_dictionary.keys()),
        'affected_rows': [int(mask.sum()) for mask in rule_dictionary.values()]
    }).sort_values('affected_rows', ascending=False)

# Example usage with your `rules` dictionary:
summarize_rule_violations(rules)